Fix/change to new logos
echo-webkom/echo-web-frontend pull request #1062
Opened 2022-04-28 15:55 UTC by sandersig

Endret til echo's nye logoer. Endret teksten de plassene på nettsiden hvor det sto "Fagutvalg" til "Linjeforening".

2022-04-28 16:04 UTC, sandersig commented
Er noen andre alternative logoer, men ingen som er identiske som den på nettsiden nå

2022-04-28 16:05 UTC, boaanes commented
Hmm, skal se om jeg finner noe

2022-04-28 16:41 UTC, boaanes commented
@sandersig vi mangler visst de logoene, skal se hva vi får gjort med det...

2022-04-28 16:42 UTC, sandersig commented
Ok. Kan fikse SEO-tags i mellomtiden

2022-04-28 16:51 UTC, boaanes commented
Du kan sikkert bare søke opp alle occurences av fagutvalget og endre det til linjeforeningen

2022-05-02 10:42 UTC, bakseter requested changes
Liten ting: det skal være "tankestrek" (–) og ikke bindestrek (-) i navnet til echo.

2022-05-02 10:42 UTC, bakseter commented on public/site.webmanifest
> +    "description": "Nettsiden til echo - Linjeforeningen for informatikk.",
```suggestion
    "name": "echo – Linjeforeningen for informatikk",
    "description": "Nettsiden til echo – Linjeforeningen for informatikk.",
```

2022-05-02 10:42 UTC, bakseter commented on src/components/seo.tsx
> +const SEO = ({ description = 'Nettsiden til echo - Linjeforeningen for informatikk.', title }: Props): JSX.Element => {
```suggestion
const SEO = ({ description = 'Nettsiden til echo – Linjeforeningen for informatikk.', title }: Props): JSX.Element => {
```

2022-05-02 10:42 UTC, bakseter commented on src/lib/generate-rss-feed.ts
> +                <title><![CDATA[echo - Linjeforeningen for informatikk]]></title>
```suggestion
                <title><![CDATA[echo – Linjeforeningen for informatikk]]></title>
```

2022-05-02 10:42 UTC, bakseter commented on src/pages/index.tsx
> +            <SEO title="echo - Linjeforeningen for informatikk" />
```suggestion
            <SEO title="echo – Linjeforeningen for informatikk" />
```

2022-05-02 10:42 UTC, bakseter commented on package.json
> +    "description": "Frontend til nettsiden til echo - Linjeforeningen for informatikk.",
```suggestion
    "description": "Frontend til nettsiden til echo – Linjeforeningen for informatikk.",
```

2022-05-02 10:44 UTC, bakseter commented
Og kanskje vente med å endre `public/static/om-oss/statutter.md` til vi har fått de nye vedtektene fra allmøtet? @boaanes

2022-05-05 12:33 UTC, bakseter approved these changes
<img src="https://media1.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/>

2022-05-05 12:49 UTC, merged