Complete refactor of static information and navigation menu
echo-webkom/echo-web-frontend pull request #1075
Opened 2022-05-02 12:18 UTC by alvarhonsi

All static information has been moved to the cms and can now be queried using the StaticInfoAPI module. All pages containing static info has been moved to the /info folder, and is routed as /info/...
The navigation menu is changed to a more usable sidebar component, which contains all relevant routes to the various static pages.

2022-05-02 15:23 UTC, boaanes requested changes
Sykt nice! Men bør kanskje finne et annet ord enn `Info` :thinking: Også bør vi ha en `Arrangementer` i navbaren også, ref #1050

2022-05-02 15:23 UTC, boaanes commented on src/components/navbar.tsx
> +            <NavLink text="Info" href="/info/om-oss" testid="om-oss" />
Kan vi ha et annet ord enn `Info`?

2022-05-02 15:23 UTC, boaanes commented on src/components/sidebar.tsx
> +    ];
Må dette hardkodes? Det kan jo fetches fra sanity?

2022-05-02 19:13 UTC, alvarhonsi commented on src/components/sidebar.tsx
> +    ];
Det burde da gå an

2022-05-04 19:08 UTC, boaanes commented
@alvarhonsi hadde vært sykt digg å fått inn det her asap

2022-05-05 13:53 UTC, bakseter commented on src/components/navbar.tsx
> +            <NavLink text="Info" href="/info/om-oss" testid="om-oss" />
Notes fra standup: kall det **Om echo**

2022-05-05 17:06 UTC, bakseter commented on src/components/sidebar.tsx
> +    ];
Det er ingen god vei rundt det fant vi ut av, bare beholder det sånn. En MVP med Sanity hadde vært å ha et JSON-felt i Sanity med hele dette objektet.

2022-05-05 17:47 UTC, bakseter approved these changes

2022-05-05 17:50 UTC, boaanes approved these changes
![I love it guy](https://media.giphy.com/media/1xpm1qOK7WuQeuK6Ub/giphy.gif)

2022-05-05 18:18 UTC, merged